### ISSUE TITLE
DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by edsvisinditus** [sk1project/wixpy#9]
Hi,

I have installed wix.py using the Windows msi installer.

When I run this command “wix.py msi.json” I get the following error:
Traceback (most recent call last):
  File "wix.py", line 32, in <module>
  File "wixpy\__init__.pyc", line 44, in <module>
  File "wixpy\model.pyc", line 22, in <module>
  File "wixpy\msi.pyc", line 28, in <module>
  File "wixpy\libmsiw.pyc", line 21, in <module>
  File "_msi.pyc", line 12, in <module>
  File "_msi.pyc", line 10, in __load
ImportError: DLL load failed: The specified module could not be found.

My msi.json file looks like this:
{
    "Name": "MyApp",
    "UpgradeCode": "3AC4B4FF-19C5-4B8F-83AD-BAC3238BF690",
    "Version": "1.0",
    "Manufacturer": "MyCompany",
    "_SourceDir": "./program",
    "_InstallDir": "myapp-1.0",
    "_OutputName": "myapp-1.0-win32.msi",
    "_OutputDir": "./"
}

Could you help me out? Thank you in advance.

**Comment by sk1project** [comment]
Hi! Please report Windows version and OS architecture (32/64bit).

**Comment by edsvisinditus** [comment]
Hi!

Thank you for getting back to me. I am running Windows 10 64 bit, version 1903.

**Comment by LazarenkoA** [comment]
I have the same problem
